### ISSUE TITLE
Problem with exponents

### ISSUE THREAD

**Issue by TomWildenhain** [BirdBrainTechnologies/BlocklyDuino-update#1]
The following code:
![image](https://cloud.githubusercontent.com/assets/13002846/8286261/7994ba20-18d6-11e5-9cbc-180abdb6fb21.png)
Compiles to:
void setup()
{
  Serial.begin(9600);
}
void loop()
{
  Serial.print((**Math.pow**(4, 2)));
  Serial.print('\t');
}
Which produces the error:
sketch.ino:9:19: error: **use of undeclared identifier 'Math'**
The Arduino code should be:
void setup()
{
  Serial.begin(9600);
}
void loop()
{
  Serial.print((**pow**(4, 2)));
  Serial.print('\t');
}
Which compiles successfully and outputs 16.

**Comment by birdbraintech** [comment]
This issue was resolved in the most recent update (coming today, already live at hummingbirdkit.com/blockly)
